# Generated by Django 4.2.8 on 2024-02-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_comment_options_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='count',
        ),
    ]
